### ISSUE TITLE
[TF2] Blocked payload cart causes segmentation fault

### ISSUE THREAD

**Issue by Thordin** [ValveSoftware/Source-1-Games#1165]
We've seen payload carts causing segmentation faults for many years now. 

We don't know what causes this but it could be related to carts getting permanently stuck or being flipped around.

```
Program terminated with signal 11, Segmentation fault.
#0  0xef22e040 in CFuncTrackTrain::Blocked(CBaseEntity*) () from tf/bin/server_srv.so
#1  0xeee05f1c in CBaseEntity::VPhysicsUpdatePusher(IPhysicsObject*) () from tf/bin/server_srv.so
#2  0xeeae5e02 in CBaseEntity::VPhysicsUpdate(IPhysicsObject*) () from tf/bin/server_srv.so
#3  0xeef5b622 in PhysFrame(float) () from tf/bin/server_srv.so
#4  0xeef5b7ca in CPhysicsHook::FrameUpdatePostEntityThink() () from tf/bin/server_srv.so
#5  0xeeb79220 in InvokePerFrameMethod(void (IGameSystemPerFrame::*)(), char const*) [clone .isra.54] () from tf/bin/server_srv.so
#6  0xeeb79617 in IGameSystem::FrameUpdatePostEntityThinkAllSystems() () from tf/bin/server_srv.so
#7  0xeee9acd6 in CServerGameDLL::GameFrame(bool) () from tf/bin/server_srv.so
#8  0xf6229105 in SV_Think(bool) () from bin/engine_srv.so
```

**Comment by kisak-valve** [comment]
Hello @Thordin, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
