### ISSUE TITLE
[TF2] - Trying to open options window crashes the game

### ISSUE THREAD

**Issue by ElectricTriangle** [ValveSoftware/Source-1-Games#1521]
After the recent Scream Fortress 2013 changes, TF2 started to crash when I tried to open the options window by clicking the options button. I also tried running the game directly using the HL2.sh file, with and without the -steam options. Oddly, running the game directly didn't produce any crashes.

I've also tried running TF2 from Steam with and without the overlay, but that didn't help. Other buttons in the interface don't seem to be crash-prone.

Running the game through Steam

```
Unable to initialize HMD tracker. Error code 108
Unable to initialize HMD tracker. Error code 108
ConVarRef hap_HasDevice doesn't point to an existing ConVar
Unable to initialize HMD tracker. Error code 108
/opt/steamdir/SteamApps/common/Team Fortress 2/hl2.sh: line 67: 19801 Aborted                 ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```

Running the game using the HL2 script

```
Unable to initialize HMD tracker. Error code 108
Unable to initialize HMD tracker. Error code 108
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
ConVarRef hap_HasDevice doesn't point to an existing ConVar
Unable to initialize HMD tracker. Error code 108
Unable to initialize HMD tracker. Error code 108
```

My system information:
https://gist.github.com/ElectricTriangle/6708900

**Comment by feilen** [comment]
I get segmentation faults in VR mode after several minutes of gameplay, for the last month or so. 

Several minutes into gameplay:

```
Core was generated by `/home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/hl2_linux -gam'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf175ed5a in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/engine.so
(gdb) where
#0  0xf175ed5a in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/engine.so
#1  0xf186afa5 in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/engine.so
#2  0xf186ce2e in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/engine.so
#3  0xf186e516 in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/engine.so
#4  0xf18729bd in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/engine.so
#5  0xf123d34e in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/materialsystem.so
#6  0xf123d69d in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/materialsystem.so
#7  0xf121d3f4 in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/materialsystem.so
#8  0xf12258ea in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/materialsystem.so
#9  0xf1225737 in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/materialsystem.so
#10 0xc3ce55e0 in ?? ()
#11 0xf30f1b9a in ?? () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/libvstdlib.so
#12 0xf31ebe00 in CThread::ThreadProc(void*) () from /home/feilen/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/libtier0.so
#13 0x4ec911a6 in start_thread () from /usr/lib32/libpthread.so.0
#14 0x4ebb881e in clone () from /usr/lib32/libc.so.6
```
Let me know if there's any other information I can provide.

**Comment by ElectricTriangle** [comment]
Unless your bug is related to trying to open the options window, you should
open a new bug and put that there instead of commenting on a closed and
completely unrelated one.

**Comment by ElectricTriangle** [comment]
Unless your bug is related to trying to open the options window, you should open a new bug and put that there instead of commenting on a closed and completely unrelated one.
