### ISSUE TITLE
Portal server.so segmentation fault after "Loading screen..." (on gentoo)

### ISSUE THREAD

**Issue by bfx81** [ValveSoftware/Source-1-Games#1813]
Even using the libraries from libc packaged in ubuntu trusty the game not start (I've recently fixed "Air Conflicts: Pacific Carriers" using those libs)
Any ideas?
Thanks in advance

Launching game log

```
bluefox@baltasar ~/.local/share/Steam/SteamApps/common/Portal $ GAME_DEBUGGER=gdb ./hl2.sh -game portal    
GNU gdb (Gentoo 7.6.2 p1) 7.6.2
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>...
Reading symbols from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/hl2_linux...(no debugging symbols found)...done.
Breakpoint 1 at 0x8048433
Setting environment variable "LD_PRELOAD" to null value.
LD_PRELOAD = 
warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, 0x08048433 in main ()
Argument list to give program being debugged when it is started is "-game portal".
(gdb) continue
Continuing.
[New Thread 0xf6d20b40 (LWP 32709)]
[New Thread 0xf651fb40 (LWP 32710)]
[New Thread 0xf613ab40 (LWP 32711)]
SDL video target is 'x11'
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0)!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
Using breakpad crash handler
Setting breakpad minidump AppID = 400
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198087560884 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198087560884
Did not detect any valid joysticks.
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 1048576, Total Avail: 1048576, Current Avail: 433608
GL_MAX_SAMPLES_EXT: 32
 failed to dlopen /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dbg.so error=/home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dbg.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dbg.so error=/home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dbg.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen stdshader_dbg.so error=stdshader_dbg.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx6.so error=/home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx6.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx6.so error=/home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx6.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen stdshader_dx6.so error=stdshader_dx6.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx7.so error=/home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx7.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx7.so error=/home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx7.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen stdshader_dx7.so error=stdshader_dx7.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx8.so error=/home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx8.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx8.so error=/home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/stdshader_dx8.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
 failed to dlopen stdshader_dx8.so error=stdshader_dx8.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
[New Thread 0xe9688b40 (LWP 32712)]
[0826/200106:ERROR:resource_bundle.cc(411)] Failed to load /home/bluefox/.local/share/Steam/SteamApps/common/Portal/cef_gtk.pak
Some features may not be available.
[New Thread 0xe93ffb40 (LWP 32713)]
[New Thread 0xe89ffb40 (LWP 32714)]
[New Thread 0xe8035b40 (LWP 32715)]
[New Thread 0xe76ffb40 (LWP 32716)]
[New Thread 0xe6cffb40 (LWP 32717)]
[New Thread 0xe62ffb40 (LWP 32718)]
[New Thread 0xe5afeb40 (LWP 32719)]
[0826/200106:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
[New Thread 0xe52fdb40 (LWP 32720)]
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 2661 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 2661 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: NO
[New Thread 0xee209b40 (LWP 32724)]
[New Thread 0xdeb52b40 (LWP 32725)]
[Thread 0xdeb52b40 (LWP 32725) exited]
[New Thread 0xdeb52b40 (LWP 32726)]
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
Could not load program cache file glshaders.cfg
Could not find user GL shader cache file
Precache: Took 0 ms, Vertex 0, Pixel 0
ConVarRef mat_dxlevel doesn't point to an existing ConVar
Game.so loaded for "Half-Life 2"
[New Thread 0xdd627b40 (LWP 32727)]
[New Thread 0xdd526b40 (LWP 32728)]
[New Thread 0xdd425b40 (LWP 32729)]
[New Thread 0xdd324b40 (LWP 32730)]
[New Thread 0xd5effb40 (LWP 32731)]

Program received signal SIGSEGV, Segmentation fault.
0xdb4963a9 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/portal/bin/server.so
(gdb) bt
#0  0xdb4963a9 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/portal/bin/server.so
#1  0xdb4964d8 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/portal/bin/server.so
#2  0xdb9af2f9 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/portal/bin/server.so
#3  0xdb46f1a8 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/portal/bin/server.so
#4  0xdb71327a in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/portal/bin/server.so
#5  0xf4a91eaa in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/engine.so
#6  0xf49b4675 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/engine.so
#7  0xf4aa7f28 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/engine.so
#8  0xf4aacb15 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/engine.so
#9  0xf4aa9fb6 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/engine.so
#10 0xf4afed20 in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/engine.so
#11 0xf4aab03f in ?? () from /home/bluefox/.local/share/Steam/SteamApps/common/Portal/bin/engine.so
#12 0xf7cddb60 in ?? () from bin/launcher.so
#13 0xf7cddb60 in ?? () from bin/launcher.so
#14 0xf7cc5d85 in LauncherMain () from bin/launcher.so
#15 0x08048474 in main ()
```

System information

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2661 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Gentoo Base System release 2.2" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.14.14-aufs
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2014-07-22

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 520/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 340.32
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1040
    Number of Monitors:  2
    Number of Video Cards Not Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 23,54" x 13,23"  (26,97" diag)
                                            59,8cm x 33,6cm  (68,5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7967 Mb

Miscellaneous:
    UI Language:  English
    LANG:  it_IT.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  918827 Mb
    Largest Free Hard Disk Block:  15906 Mb
```

**Comment by kisak-valve** [comment]
Hello @bfx81, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by bfx81** [comment]
Sorry... really miss the notification. Well yes... tried (after an update) and still the same problem.
