### ISSUE TITLE
Portal crash when launch

### ISSUE THREAD

**Issue by YangtseSu** [ValveSoftware/Source-1-Games#2284]
Archlinux x86_64 nvidia,had s3tc installed.

GameAction [AppID 400, ActionID 2] : LaunchApp changed task to Starting with ""
GameAction [AppID 400, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 400, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 400, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 400, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 400 "Portal", ProcID 6067, IP 0.0.0.0:0
>>> Adding process 6067 for game ID 400
GameAction [AppID 400, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/yangtse/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 400, ActionID 2] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/yangtse/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 6068 for game ID 400
ERROR: ld.so: object '/home/yangtse/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 6094 != 6087, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/yangtse/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/yangtse/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 6087 for game ID 400
>>> Adding process 6095 for game ID 400
>>> Adding process 6100 for game ID 400
SDL video target is 'x11'
SDL video target is 'x11'
Using breakpad crash handler
Setting breakpad minidump AppID = 400
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Game update: AppID 400 "Portal", ProcID 6100, IP 0.0.0.0:0
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198048642417 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198048642417
Did not detect any valid joysticks.

(hl2_linux:6100): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(hl2_linux:6100): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
[0526/084914:ERROR:resource_bundle.cc(411)] Failed to load /home/yangtse/.local/share/Steam/SteamApps/common/Portal/cef_gtk.pak
Some features may not be available.
[0526/084914:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 8
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3100 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3100 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: YES

 ##### swap interval = 0     swap limit = 1 #####
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
Could not load program cache file glshaders.cfg
Could not find user GL shader cache file
Precache: Took 0 ms, Vertex 0, Pixel 0
ConVarRef mat_dxlevel doesn't point to an existing ConVar
Game.so loaded for "Half-Life 2"
ERROR: ld.so: object '/home/yangtse/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20170526084911_1.dmp[6164]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170526084911_1.dmp
>>> Adding process 6163 for game ID 400
/home/yangtse/.local/share/Steam/SteamApps/common/Portal/hl2.sh: 行 67:  6100 段错误               (核心已转储)${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 400 "Portal", ProcID 6100 
No cached sticky mapping in ActivateActionSet.crash_20170526084911_1.dmp[6164]: Finished uploading minidump (out-of-process): success = yes
crash_20170526084911_1.dmp[6164]: response: CrashID=bp-a4c61186-2f30-4210-9376-875fd2170525
crash_20170526084911_1.dmp[6164]: file ''/tmp/dumps/crash_20170526084911_1.dmp'', upload yes: ''CrashID=bp-a4c61186-2f30-4210-9376-875fd2170525''
pid 6164 != 6163, skipping destruction (fork without exec?)

**Comment by kisak-valve** [comment]
[System info](https://github.com/ValveSoftware/Dota-2/files/1030535/sysinfo.txt) from https://github.com/ValveSoftware/Dota-2/issues/1240#issuecomment-304163090.

**Comment by kisak-valve** [comment]
Hello @YangtseSu, the mismatch between your system information and the start of this issue report hints that you are using an Optimus laptop. How are you telling the game to run on the game to run on the nvidia gpu, and can you check that you have the 32 bit nvidia libraries?

If possible, it would be nice if you confirmed that a 32 bit opengl application works on the nvidia gpu outside of steam.

**Comment by eriktorbjorn** [comment]
I'm also having problems with Portal crashing on startup, but I don't know if it's the same crash. (What _is_ the proper way of starting the game from a command prompt to get useful debug info anyway?)

Now, since I'm running Debian sid I _probably_ don't fulfil the system requirements for the game. I say "probably" because at the moment the system requirements for Linux aren't listed on the store page. However, it _used_ to work flawlessly, so perhaps it's something that eventually will happen even on supperted Linux distributions.

The best description I've found for my problem is https://steamcommunity.com/app/400/discussions/0/1471967615846108549/

It gets as far as showing a blurry background during loading, but as soon as it's supposed to show the sharp version and main menu it crashes. Unless it's the "cake" background, or I use the -nosound command-line option. In both these cases it seems to work.

Is this the same problem as described in this bug report, or should I file a separate one?

[system-info.txt](https://github.com/ValveSoftware/Source-1-Games/files/1654705/system-info.txt)

**Comment by kisak-valve** [comment]
Hello @eriktorbjorn, probably best to investigate separately in a new issue report.

You should be able run `<steam folder>/ubuntu12_32/steam-runtime/run.sh ./hl2.sh` in a terminal while steam is running to run the game in a similar environment as running from Steam. If you happen to find any CrashIDs or minidumps related to your issue, please include them.

**Comment by eriktorbjorn** [comment]
Thanks! I had to add "-game portal" to that command-line for it to work, but I assume that's what you meant. I've attached the output from that command (portal-crash.txt), the output from also adding "-nosound" just for comparison, and the crash dump that the first output referred to.

Interestingly, it crashed in both runs but with -nosound it didn't crash until I quit the game, so it wasn't very noticeable.

Is there a way to force the "cake" background? The one time I got that intead of the normal one, it didn't crash. At least not on the main menu.

[portal-crash.txt](https://github.com/ValveSoftware/Source-1-Games/files/1657264/portal-crash.txt)
[portal-nosound.txt](https://github.com/ValveSoftware/Source-1-Games/files/1657265/portal-nosound.txt)
[crash_20180123195926_1.dmp.gz](https://github.com/ValveSoftware/Source-1-Games/files/1657267/crash_20180123195926_1.dmp.gz)

**Comment by kisak-valve** [comment]
@eriktorbjorn, I have a hunch that you're seeing a variant of https://github.com/ValveSoftware/steam-for-linux/issues/5330#issuecomment-359758928. Might as well do a test with `GLIBC_TUNABLES=glibc.tune.hwcaps=-SSE4_2 steam` and see if it makes a difference.

For reference, the attached minidump is a SIGSEGV in libc-2.26.so coming from filesystem_stdio.so (part of Portal).

**Comment by eriktorbjorn** [comment]
Thanks, that did work! Even better, from that page you referred to I got to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887327 where they say that "it looks like fixing PR81481 [1] on the GCC 7 side, and then rebuilding glibc is the way to go".

Well, after I tried your solution I checked for updates, and it turns out that there were updates for both GCC and glibc. And now - probably because of that - Portal works again without the workaround.

Of course, I still have no idea if this is relevant to the actual bug report here, since it could be an entirely different "Portal crash when launch" issue.

**Comment by phkb01** [comment]
I also have a crash; same error message about cef_gtk.pak, but different backtrace. Here is the info:

```
Did not detect any valid joysticks.
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 16
[New Thread 0xeb2dfb40 (LWP 15010)]
[0729/112016:ERROR:resource_bundle.cc(411)] Failed to load /home/games/.local/share/Steam/steamapps/common/Portal/cef_gtk.pak
Some features may not be available.
[New Thread 0xeb1deb40 (LWP 15011)]
[New Thread 0xea7ffb40 (LWP 15012)]
[New Thread 0xe9ffeb40 (LWP 15013)]
[New Thread 0xe97fdb40 (LWP 15014)]
[0729/112016:FATAL:message.cc(253)] Check failed: success. Unable to allocate memory

Thread 11 "NetworkChangeNo" received signal SIGABRT, Aborted.
[Switching to Thread 0xe9ffeb40 (LWP 15013)]
0xf7fd3939 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fd3939 in __kernel_vsyscall ()
#1  0xf7ddb8f2 in __libc_signal_restore_set (set=0xe9ffd96c) at ../sysdeps/unix/sysv/linux/internal-signals.h:84
#2  __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xf7dc4309 in __GI_abort () at abort.c:79
#4  0xef07f2d9 in  () at /home/games/.local/share/Steam/steamapps/common/Portal/bin/libcef.so
#5  0xef0939ce in  () at /home/games/.local/share/Steam/steamapps/common/Portal/bin/libcef.so
#6  0xefa5e7d1 in  () at /home/games/.local/share/Steam/steamapps/common/Portal/bin/libcef.so
#7  0xefa5eaf3 in  () at /home/games/.local/share/Steam/steamapps/common/Portal/bin/libcef.so
#8  0xef17a96d in  () at /home/games/.local/share/Steam/steamapps/common/Portal/bin/libcef.so
#9  0xef0b77a5 in  () at /home/games/.local/share/Steam/steamapps/common/Portal/bin/libcef.so
#10 0xef0b6a12 in  () at /home/games/.local/share/Steam/steamapps/common/Portal/bin/libcef.so
#11 0xf7d91094 in start_thread (arg=<optimized out>) at pthread_create.c:479
#12 0xf7ea7e46 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108
```

System config:
- Steam: Jul 28 2020, at 22:37:46
- Kernel: 5.4.48
- Distro: gentoo
- Graphics: optimus laptop with Nvidia GTX 1660 Ti (tried on both discrete and integrated graphics, got the crash on both)

I'm happy to provide more information and/or do more debugging if needed.
