### ISSUE TITLE
Left 4 Dead 2 dedicated linux server segmentation fault at every start

### ISSUE THREAD

**Issue by gionn** [ValveSoftware/Source-1-Games#2745]
Hi,

I was trying to use L4D2 dedicated server under Docker, but I am getting a segfault at every start:

```
Setting breakpad minidump AppID = 222860
Using breakpad crash handler
Forcing breakpad minidump interfaces to load
dlopen failed trying to load:
/home/steam/.steam/sdk32/steamclient.so
with error:
/home/steam/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Segmentation fault (core dumped)
Add "-debug" to the /home/steam/app/srcds_run command line to generate a debug.log to help with solving this problem
Wed Jan 27 07:30:06 UTC 2016: Server restart in 10 seconds
```

The [Dockerfile](https://github.com/zobees/docker-steamcmd/blob/master/Dockerfile) contains references for the environment.

I've never tried this before so, maybe or not be a glitch with the current version of L4D2 server, however with the same method I've got Team Fortress 2 working like a charm.

Replicate with:

```
docker run --name l4d2 -d -p 27015:27015/udp -p 27015:27015 -e STEAM_APP_ID=222860 -e STEAM_USERNAME=anonymous -e "STEAM_APP_CMD=./app/srcds_run -game left4dead2 " -v /var/local/docker/l4d2:/home/steam/app zobees/steamcmd
```

The folder `/var/local/docker/l4d2` should be 777 on docker host.

Let me know if I can do something to ease debug.

**Comment by ceifa** [comment]
The problem still happening:

> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  0xf7dc4c52 in ?? ()
> [Current thread is 1 (LWP 149)]
> #0  0xf7dc4c52 in ?? ()
> Backtrace stopped: Cannot access memory at address 0xff803d78
> No symbol table info available.
> eax            0x1e34b0cc	506769612
> ecx            0x4	4
> edx            0xff806460	-8362912
> ebx            0xf7899000	-141979648
> esp            0xff803d78	0xff803d78
> ebp            0xff80b278	0xff80b278
> esi            0xff806490	-8362864
> edi            0x4	4
> eip            0xf7dc4c52	0xf7dc4c52
> eflags         0x210202	[ IF RF ID ]
> cs             0x23	35
> ss             0x2b	43
> ds             0x2b	43
> es             0x2b	43
> fs             0x0	0
> gs             0x63	99
> No shared libraries loaded at this time.
> End of Source crash report
> ----------------------------------------------
>
