### ISSUE TITLE
Left 4 Dead 2 dedicated linux server segmentation fault at changelevel

### ISSUE THREAD

**Issue by BraveSail** [ValveSoftware/Source-1-Games#3236]
Hello, my linux dedicated server sometimes crash during map transition:

----------------------------------------------
CRASH: Tue 14 Apr 2020 10:06:28 AM CST
Start Line: ./srcds_linux -debug debug.log -insecure -tickrate 64 -game left4dead2 +exec server.cfg +map c1m1 +port 23333 +maxplayers 32
[New LWP 7626]
[New LWP 7668]
[New LWP 7675]
[New LWP 7670]
[New LWP 7637]
[New LWP 8496]
[New LWP 7635]
[New LWP 19362]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by ./srcds_linux -debug debug.log -insecure -tickrate 64 -game left4dead2 +exec se.
Program terminated with signal SIGABRT, Aborted.
#0  0xf7f37069 in __kernel_vsyscall ()
[Current thread is 1 (Thread 0xf7b63940 (LWP 7626))]
#0  0xf7f37069 in __kernel_vsyscall ()
#1  0xf7baa202 in raise () from /lib32/libc.so.6
#2  0xf7b942b6 in abort () from /lib32/libc.so.6
#3  0xf7bebb0c in ?? () from /lib32/libc.so.6
#4  0xf7bf2a7d in ?? () from /lib32/libc.so.6
#5  0xf7bf418b in ?? () from /lib32/libc.so.6
#6  0xf7e009d9 in operator delete (ptr=0x11be9540) at /valve/build/targets/src/gcc-4.6.1/libstdc++-v3/libsupc++/del_op.cc:47
#7  0xf7e00a23 in operator delete[] (ptr=0x11be9540) at /valve/build/targets/src/gcc-4.6.1/libstdc++-v3/libsupc++/del_opv.cc:32
#8  0xf5412cbf in CPhysicsCollision::VCollideUnload(vcollide_t*) () from /home/a/l4d2/bin/vphysics_srv.so
#9  0xf7258b55 in CollisionBSPData_Destroy(CCollisionBSPData*) () from /home/a/l4d2/bin/engine_srv.so
#10 0xf7251eb2 in CM_FreeMap() () from /home/a/l4d2/bin/engine_srv.so
#11 0xf72aef05 in Host_FreeToLowMark(bool) () from /home/a/l4d2/bin/engine_srv.so
#12 0xf7329556 in CGameServer::SpawnServer(char*, char*) () from /home/a/l4d2/bin/engine_srv.so
#13 0xf72aed2e in Host_Changelevel(bool, char const*, char const*) () from /home/a/l4d2/bin/engine_srv.so
#14 0xf72b7952 in CHostState::State_ChangeLevelMP() () from /home/a/l4d2/bin/engine_srv.so
#15 0xf72b7d41 in CHostState::FrameUpdate(float) () from /home/a/l4d2/bin/engine_srv.so
#16 0xf72b7e19 in HostState_Frame(float) () from /home/a/l4d2/bin/engine_srv.so
#17 0xf7343bd3 in CEngine::Frame() () from /home/a/l4d2/bin/engine_srv.so
#18 0xf7340ca6 in CDedicatedServerAPI::RunFrame() () from /home/a/l4d2/bin/engine_srv.so
#19 0xf75bf6ac in RunServerIteration(bool) () from bin/dedicated_srv.so
#20 0xf75bf748 in RunServer(bool) () from bin/dedicated_srv.so
#21 0xf7340d8d in CModAppSystemGroup::Main() () from /home/a/l4d2/bin/engine_srv.so
#22 0xf7392200 in CAppSystemGroup::Run() () from /home/a/l4d2/bin/engine_srv.so
#23 0xf7341b9f in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /home/a/l4d2/bin/engine_srv.so
#24 0xf75bf820 in CDedicatedAppSystemGroup::Main() () from bin/dedicated_srv.so
#25 0xf75de900 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#26 0xf75de900 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#27 0xf758b0f5 in main () from bin/dedicated_srv.so
#28 0x080486f1 in main ()
No symbol table info available.
eax            0x0                 0
ecx            0xff90549c          -7318372
edx            0x0                 0
ebx            0x2                 2
esp            0xff905480          0xff905480
ebp            0xff90549c          0xff90549c
esi            0x8                 8
edi            0x0                 0
eip            0xf7f37069          0xf7f37069 <__kernel_vsyscall+9>
eflags         0x200282            [ SF IF ID ]
cs             0x23                35
ss             0x2b                43
ds             0x2b                43
es             0x2b                43
fs             0x0                 0
gs             0x63                99
From        To          Syms Read   Shared Object Library
0xf7e5d170  0xf7ee529f  Yes (*)     /lib32/libm.so.6
0xf7e4e130  0xf7e4f1c4  Yes (*)     /lib32/libdl.so.2
0xf7dc0914  0xf7e06c78  Yes         bin/libstdc++.so.6
0xf7d5e5e0  0xf7d6de9f  Yes         /lib32/libpthread.so.0
0xf7b940e0  0xf7ce0776  Yes (*)     /lib32/libc.so.6
0xf7f39090  0xf7f5450b  Yes (*)     /lib/ld-linux.so.2
0xf7b66e00  0xf7b760fc  Yes         bin/libgcc_s.so.1
0xf7b38ea0  0xf7b4d118  Yes (*)     bin/libtier0_srv.so
0xf7b263d0  0xf7b29cb4  Yes (*)     /lib32/librt.so.1
0xf7a3ee20  0xf7a61104  Yes (*)     bin/libvstdlib_srv.so
0xf758a360  0xf75f8298  Yes (*)     bin/dedicated_srv.so
0xf7543ea0  0xf75593d4  Yes (*)     bin/libsteam_api.so
0xf71c8ce0  0xf73c4a90  Yes (*)     /home/a/l4d2/bin/engine_srv.so
0xf6c7bbb0  0xf6ca4d20  Yes (*)     /home/a/l4d2/bin/soundemittersystem_srv.so
0xf6b0ee00  0xf6bcb394  Yes (*)     /home/a/l4d2/bin/materialsystem_srv.so
0xf55d2410  0xf5675340  Yes (*)     /home/a/l4d2/bin/studiorender_srv.so
0xf5387840  0xf551f548  Yes (*)     /home/a/l4d2/bin/vphysics_srv.so
0xf52c7a00  0xf53191e0  Yes (*)     /home/a/l4d2/bin/datacache_srv.so
0xf520d150  0xf5277a18  Yes (*)     /home/a/l4d2/bin/vscript_srv.so
0xf51dd340  0xf51ed4e4  Yes (*)     /home/a/l4d2/bin/shaderapiempty_srv.so
0xef46e9c0  0xf00b3a44  Yes (*)     bin/steamclient.so
0xef3276c0  0xef39c6b0  Yes (*)     bin/crashhandler.so
0xeec4cb00  0xeecc3b98  Yes (*)     /home/a/l4d2/left4dead2/bin/matchmaking_ds_srv.so
0xedf7deb0  0xee7c077c  Yes (*)     /home/a/l4d2/left4dead2/bin/server_srv.so
0xedc13c10  0xedc23084  Yes (*)     /home/a/l4d2/bin/scenefilecache_srv.so
0xf6c60100  0xf6c61c2d  Yes (*)     /home/a/l4d2/left4dead2/addons/metamod/bin/server.so
0xe9854d40  0xe9881182  Yes (*)     /home/a/l4d2/left4dead2/addons/metamod/bin/metamod.2.l4d2.so
0xe9805eb0  0xe982d4c0  Yes (*)     /home/a/l4d2/left4dead2/addons/tickrate_enabler/tickrate_enabler.so
0xf6c4c300  0xf6c52cc4  Yes (*)     /lib32/libnss_files.so.2
0xf7f2e950  0xf7f2eea9  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/bin/sourcemod_mm_i486.so
0xe966f2c0  0xe96d65c2  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/bin/sourcemod.2.l4d2.so
0xe9492960  0xe94eae40  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/bin/sourcemod.logic.so
0xe96172e0  0xe964114c  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/bin/sourcepawn.jit.x86.so
0xf7f294a0  0xf7f2c3a4  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/updater.ext.so
0xe916ba50  0xe9194655  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/webternet.ext.so
0xe81445c0  0xe8159808  Yes (*)     /home/a/l4d2/left4dead2/addons/l4dtoolz/l4dtoolz_mm.so
0xf6c431c0  0xf6c461f4  Yes (*)     /lib32/libnss_dns.so.2
0xe81253a0  0xe8131014  Yes (*)     /lib32/libresolv.so.2
0xe9609670  0xe960bcf2  Yes         /home/a/l4d2/left4dead2/addons/sourcemod/extensions/l4d2_bugfixes.ext.2.l4d2.so
0xe9602a70  0xe96045a4  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/cleaner.ext.2.l4d2.so
0xe811aae0  0xe811f7e4  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/clientprefs.ext.so
0xe7aed9d0  0xe7bfe010  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/dbi.sqlite.ext.so
0xe6ec0180  0xe6ee9762  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/sdkhooks.ext.2.l4d2.so
0xf7f23ac0  0xf7f260e4  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/bintools.ext.so
0xe7d56520  0xe7d91f42  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/sdktools.ext.2.l4d2.so
0xe8110700  0xe8116ec8  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/topmenus.ext.so
0xe7ee1860  0xe7ef4cf4  Yes         /home/a/l4d2/left4dead2/addons/sourcemod/extensions/dhooks.ext.so
0xe8108e80  0xe810b7c8  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/geoip.ext.so
0xe2deab50  0xe2e7fa65  Yes (*)     /home/a/l4d2/left4dead2/addons/sourcemod/extensions/dbi.mysql.ext.so
0xe7d1baa0  0xe7d2e9a9  Yes (*)     /lib32/libz.so.1
(*): Shared library is missing debugging information.
Dump of assembler code for function __kernel_vsyscall:
   0xf7f37060 <+0>:	push   %ecx
   0xf7f37061 <+1>:	push   %edx
   0xf7f37062 <+2>:	push   %ebp
   0xf7f37063 <+3>:	mov    %esp,%ebp
   0xf7f37065 <+5>:	sysenter 
   0xf7f37067 <+7>:	int    $0x80
=> 0xf7f37069 <+9>:	pop    %ebp
   0xf7f3706a <+10>:	pop    %edx
   0xf7f3706b <+11>:	pop    %ecx
   0xf7f3706c <+12>:	ret    
End of assembler dump.
Stack level 0, frame at 0xff905490:
 eip = 0xf7f37069 in __kernel_vsyscall; saved eip = 0xf7baa202
 called by frame at 0xff9055c0
 Arglist at 0xff905488, args: 
 Locals at 0xff905488, Previous frame's sp is 0xff905490
 Saved registers:
  ecx at 0xff905488, edx at 0xff905484, ebp at 0xff905480, eip at 0xff90548c
End of Source crash report
----------------------------------------------
[debug.log](https://github.com/ValveSoftware/Source-1-Games/files/4474216/debug.log)

This does not happen every time, sometimes 5min, sometimes 2hours.

**Comment by BraveSail** [comment]
[Current thread is 1 (Thread 0xf7bce940 (LWP 12262))]
#0  0xf7fa2069 in __kernel_vsyscall ()
#1  0xf7c15202 in raise () from /lib32/libc.so.6
#2  0xf7bff2b6 in abort () from /lib32/libc.so.6
#3  0xf7c56b0c in ?? () from /lib32/libc.so.6
#4  0xf7c5da7d in ?? () from /lib32/libc.so.6
#5  0xf7c5f41b in ?? () from /lib32/libc.so.6
#6  0xf7299e0f in CUtlMemory<unsigned char, int>::Purge() () from /home/a/l4d22/bin/engine_srv.so
#7  0xf7344a72 in CNetworkStringTableDictionaryManager::Clear() () from /home/a/l4d22/bin/engine_srv.so
#8  0xf7346f9f in CNetworkStringTableDictionaryManager::LoadMapStrings(char const*) () from /home/a/l4d22/bin/engine_srv.so
#9  0xf7347147 in CNetworkStringTableDictionaryManager::OnLevelLoadStart(char const*, unsigned long*) () from /home/a/l4d22/bin/engine_srv.so
#10 0xf734b831 in SV_CreateNetworkStringTables(char const*) () from /home/a/l4d22/bin/engine_srv.so
#11 0xf73948ed in CGameServer::SpawnServer(char*, char*) () from /home/a/l4d22/bin/engine_srv.so
#12 0xf7319d2e in Host_Changelevel(bool, char const*, char const*) () from /home/a/l4d22/bin/engine_srv.so
#13 0xf7322952 in CHostState::State_ChangeLevelMP() () from /home/a/l4d22/bin/engine_srv.so
#14 0xf7322d41 in CHostState::FrameUpdate(float) () from /home/a/l4d22/bin/engine_srv.so
#15 0xf7322e19 in HostState_Frame(float) () from /home/a/l4d22/bin/engine_srv.so
#16 0xf73aebd3 in CEngine::Frame() () from /home/a/l4d22/bin/engine_srv.so
#17 0xf73abca6 in CDedicatedServerAPI::RunFrame() () from /home/a/l4d22/bin/engine_srv.so
#18 0xf762a6ac in RunServerIteration(bool) () from bin/dedicated_srv.so
#19 0xf762a748 in RunServer(bool) () from bin/dedicated_srv.so
#20 0xf73abd8d in CModAppSystemGroup::Main() () from /home/a/l4d22/bin/engine_srv.so
#21 0xf73fd200 in CAppSystemGroup::Run() () from /home/a/l4d22/bin/engine_srv.so
#22 0xf73acb9f in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /home/a/l4d22/bin/engine_srv.so
#23 0xf762a820 in CDedicatedAppSystemGroup::Main() () from bin/dedicated_srv.so
#24 0xf7649900 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#25 0xf7649900 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#26 0xf75f60f5 in main () from bin/dedicated_srv.so
#27 0x080486f1 in main ()
No symbol table info available.
