### ISSUE TITLE
[TF2] NULL pointer dereference on linux in CEconItemDescription's method

### ISSUE THREAD

**Issue by fe7ch** [ValveSoftware/Source-1-Games#3486]
OS: Ubuntu 18.04

The crash happens in the following code block of client.so:
```
.text:00BB5AD0                 mov     eax, off_1F7C3E8
.text:00BB5AD5                 lea     ecx, [ebp+var_C40]
.text:00BB5ADB                 mov     ebx, [edi+10h]
.text:00BB5ADE                 mov     eax, [eax+4]
.text:00BB5AE1                 mov     edx, [eax]    <----  here
.text:00BB5AE3                 mov     [esp], ecx
.text:00BB5AE6                 mov     [esp+4], eax
.text:00BB5AEA                 call    dword ptr [edx+8]
```

eax value is 0.

Stack trace:
```
#0  0xe8610ae1 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#1  0xe860d32e in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#2  0xe860e24e in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#3  0xe860bc70 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#4  0xe866c0f5 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#5  0xe866c1e2 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#6  0xe8cdba47 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#7  0xe8f99fd7 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#8  0xe8f9a0e2 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#9  0xe8cdd74b in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#10 0xe8cdd938 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#11 0xebd60a5c in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#12 0xebd60aa8 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#13 0xebd60aa8 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#14 0xebd60aa8 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#15 0xebd60aa8 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#16 0xebd60aa8 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#17 0xebd60aa8 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#18 0xebd60aa8 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#19 0xebd60ff9 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#20 0xebbb9ac6 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/vgui2.so
#21 0xee48569d in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/engine.so
#22 0xee56e966 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/engine.so
#23 0xee657be3 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/engine.so
#24 0xee65cc0f in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/engine.so
#25 0xee659801 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/engine.so
#26 0xee6c1b48 in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/engine.so
#27 0xee65b53f in ?? () from /home/fetch/.steam/steam/steamapps/common/Team Fortress 2/bin/engine.so
#28 0xf7abf778 in ?? () from bin/launcher.so
#29 0xf7abf778 in ?? () from bin/launcher.so
#30 0xf7a9f966 in LauncherMain () from bin/launcher.so
#31 0x080487ed in main ()
```

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by kisak-valve** [comment]
Closing pending feedback.
