### ISSUE TITLE
[L4D2] Crashes when DualSense controller is connected

### ISSUE THREAD

**Issue by xDShot** [ValveSoftware/Source-1-Games#3591]
Happens since last update

To reproduce:
Plug the controller.
Launch game
Crashes on loading screen

Another case:
Unplug controller
Launch game
Plug controller
Crashes few seconds later

**Comment by xDShot** [comment]
backtrace
```
(gdb) bt
#0  __strlen_ia32 () at ../sysdeps/i386/i586/strlen.S:64
#1  0xf7cd0e19 in __vfprintf_internal (s=<optimized out>, format=<optimized out>, ap=<optimized out>, mode_flags=<optimized out>) at vfprintf-internal.c:1647
#2  0xf7ce210c in __vsnprintf_internal (string=0xbc2859f "", maxlen=<optimized out>, format=0xaca044aa "%s", args=0xffaa156c "/vgu", mode_flags=0) at vsnprintf.c:114
#3  0xf7ce217e in ___vsnprintf (string=0xbc2859f "", maxlen=256, format=0xaca044aa "%s", args=0xffaa156c "/vgu") at vsnprintf.c:124
#4  0xac7bac98 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#5  0xac728a26 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#6  0xac73cc87 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#7  0xac8df189 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#8  0xac8d627e in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#9  0xac8d6267 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#10 0xac5dba6d in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#11 0xac4646e8 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#12 0xac4645c3 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#13 0xac46465b in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#14 0xac43fd72 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#15 0xac44064d in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/left4dead2/bin/client.so
#16 0xd9665e4b in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/bin/engine.so
#17 0xd976a547 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/bin/engine.so
#18 0xd986c92c in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/bin/engine.so
#19 0xd9871ca7 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/bin/engine.so
#20 0xd986e478 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/bin/engine.so
#21 0xd98e3958 in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/bin/engine.so
#22 0xd986fc3f in ?? () from /evo/SteamLibrary/steamapps/common/Left 4 Dead 2/bin/engine.so
#23 0xf61b2718 in ?? () from bin/launcher.so
#24 0xf61b2718 in ?? () from bin/launcher.so
#25 0xf619897e in LauncherMain () from bin/launcher.so
#26 0x080484c4 in main ()
(gdb)
```

**Comment by mustymaster** [comment]
have you tried verifying the game files or checking which beta version you are using if you are using a beta version at all?

**Comment by xDShot** [comment]
same

**Comment by xDShot** [comment]
It doesn't crash if I import Gamepad template in Steam Controller Options but then It doesn't show controller buttons prompts killing all of it's purpose.

**Comment by xDShot** [comment]
To add some more weirdness:

If import gamepad config, then launch game, them import official one configuration:
- It works
- Input is duplicated along with steam controller and generic(?) gamepad

So, the controller support is very broken in the game. I guess they shouldn't had to push the update that fast without proper testings.

**Comment by xDShot** [comment]
Doubled input is fixed by disabling Gamepad in options. Controller input is still recognized.

**Comment by mustymaster** [comment]
life is a unsolved mystery ma man

**Comment by xDShot** [comment]
Stopped crashing, thanks. Feels awesome!
