### ISSUE TITLE
[HL2] SIGSEGV on Linux with OpenGL

### ISSUE THREAD

**Issue by pointydev** [ValveSoftware/Source-1-Games#6764]
**Description**
When loading certain maps while using OpenGL (the default in my configuration), the game segfaults instantly. On other maps, the game freezes momentarily before continuing, which seems to mitigate the bug on other maps. If the Steam overlay is enabled, it will also display red boxes on the screen instead of the contents of the overlay. This crash is mitigated by using `-vulkan` in launch options.

Command line log:
```
Dropped blunt pointy object from server (Disconnect by user.)
Unknown command "#====================================================================="
Error reading weapon data file for: weapon_oldmanharpoon
Error: Material "models/eli/pupil_r" uses unknown shader "Eyeball"
Error: Material "models/eli/pupil_l" uses unknown shader "Eyeball"
Error: Material "models/mossman/pupil_r" uses unknown shader "Eyeball"
Error: Material "models/mossman/pupil_l" uses unknown shader "EyeballERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
crash_20241127010835_2.dmp[14011]: Uploading dump (out-of-process)
/tmp/dumps/crash_20241127010835_2.dmp
crash_20241127010835_2.dmp[14011]: Finished uploading minidump (out-of-process): success = yes
crash_20241127010835_2.dmp[14011]: response: CrashID=bp-9ee5ae26-779f-4958-b080-90fdd2241126
crash_20241127010835_2.dmp[14011]: file ''/tmp/dumps/crash_20241127010835_2.dmp'', upload yes: ''CrashID=bp-9ee5ae26-779f-4958-b080-90fdd2241126''
pid 14011 != 14010, skipping destruction (fork without exec?)
/home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/hl2.sh: line 87: 13877 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```

Backtrace:
```
#0  0xf7cea9a6 in ?? ()
#1  0xe880986d in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/shaderapidx9.so
#2  0xe880dde8 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/shaderapidx9.so
#3  0xe880dec9 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/shaderapidx9.so
#4  0xe9123350 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/studiorender.so
#5  0xe91246fc in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/studiorender.so
#6  0xe91279c7 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/studiorender.so
#7  0xe9127ce9 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/studiorender.so
#8  0xe91280d2 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/studiorender.so
#9  0xe9128411 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/studiorender.so
#10 0xe918c08b in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/studiorender.so
#11 0xe9194909 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/studiorender.so
#12 0xea5b5b0c in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/materialsystem.so
#13 0xea5b5e0f in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/materialsystem.so
#14 0xea58f507 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/materialsystem.so
#15 0xea5985d7 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/materialsystem.so
#16 0xea598505 in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/materialsystem.so
#17 0xf6233a7e in ?? () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/libvstdlib.so
#18 0xf6336b29 in CThread::ThreadProc(void*) () from /home/pointy/.local/share/Steam/steamapps/common/Half-Life 2/bin/libtier0.so
#19 0xf7cd4b33 in ?? ()
#20 0xf7d5bdf8 in ?? ()
```
Screenshots:
- Screen immediately before crash
![Screen immediately before crash](https://github.com/user-attachments/assets/58df00b4-8bdb-4911-8310-99d1b1e3ed0f)
- Overlay artifacts on main menu
![Overlay artifacts on main menu](https://github.com/user-attachments/assets/4387223a-27fa-4f6d-afe6-1a50134013bd)
- Open overlay artifacts
![Open overlay artifacts](https://github.com/user-attachments/assets/7e0f377b-d033-4785-a15b-ddfeea83630d)

**Steps to reproduce**
1) Launch Half-Life 2 using OpenGL (easy to confirm by checking the window title)
2) Start a new game on "A Red Letter Day"/`map d1_trainstation_05`
    - If you would like to test the freezing, start a new game on Point Insertion
3) Observe

**System information**
* Steam: https://gist.github.com/pointydev/64d705b020b3d3ba64a37ac4ea92194c
* Half-Life 2: build 9375045 ([November 26, 2024 Update](https://steamdb.info/patchnotes/16545043/))
    * Doesn't occur on build 9353166 ([November 18, 2024 Update](https://steamdb.info/patchnotes/16446692/))

Thanks,
Elliott

**Comment by JeremyLeland** [comment]
This started crashing for me after the latest update as well (and the -vulkan mitigation works for me, thank you for that!)

It started crashing on my Debian 12 install: https://gist.github.com/JeremyLeland/ca50df285f21fcc80b20da935b2b0bfa

However, it still works on my Fedora 40 install: https://gist.github.com/JeremyLeland/70a49925dcb5ac51d05251d2325bbeea

The two installs are on different physical hard drives but use the same hardware otherwise.
